export enum PURCHASE_TYPE {
    INAPP = "inapp",
    SUBS = "subs"
}

export enum BILLING_FEATURE {
    SUBSCRIPTIONS = 0,
    SUBSCRIPTIONS_UPDATE = 1,
    IN_APP_ITEMS_ON_VR = 2,
    SUBSCRIPTIONS_ON_VR = 3,
    PRICE_CHANGE_CONFIRMATION = 4
}

export enum PURCHASES_ERROR_CODE {
    UNKNOWN_ERROR = "0",
    PURCHASE_CANCELLED_ERROR = "1",
    STORE_PROBLEM_ERROR = "2",
    PURCHASE_NOT_ALLOWED_ERROR = "3",
    PURCHASE_INVALID_ERROR = "4",
    PRODUCT_NOT_AVAILABLE_FOR_PURCHASE_ERROR = "5",
    PRODUCT_ALREADY_PURCHASED_ERROR = "6",
    RECEIPT_ALREADY_IN_USE_ERROR = "7",
    INVALID_RECEIPT_ERROR = "8",
    MISSING_RECEIPT_FILE_ERROR = "9",
    NETWORK_ERROR = "10",
    INVALID_CREDENTIALS_ERROR = "11",
    UNEXPECTED_BACKEND_RESPONSE_ERROR = "12",
    RECEIPT_IN_USE_BY_OTHER_SUBSCRIBER_ERROR = "13",
    INVALID_APP_USER_ID_ERROR = "14",
    OPERATION_ALREADY_IN_PROGRESS_ERROR = "15",
    UNKNOWN_BACKEND_ERROR = "16"
}

export enum PACKAGE_TYPE {
    UNKNOWN = "UNKNOWN",
    CUSTOM = "CUSTOM",
    LIFETIME = "LIFETIME",
    ANNUAL = "ANNUAL",
    SIX_MONTH = "SIX_MONTH",
    THREE_MONTH = "THREE_MONTH",
    TWO_MONTH = "TWO_MONTH",
    MONTHLY = "MONTHLY",
    WEEKLY = "WEEKLY"
}

export enum PRODUCT_CATEGORY {
    NON_SUBSCRIPTION = "NON_SUBSCRIPTION",
    SUBSCRIPTION = "SUBSCRIPTION",
    UNKNOWN = "UNKNOWN"
}

export enum PRODUCT_TYPE {
    CONSUMABLE = "CONSUMABLE",
    NON_CONSUMABLE = "NON_CONSUMABLE",
    NON_RENEWABLE_SUBSCRIPTION = "NON_RENEWABLE_SUBSCRIPTION",
    AUTO_RENEWABLE_SUBSCRIPTION = "AUTO_RENEWABLE_SUBSCRIPTION",
    PREPAID_SUBSCRIPTION = "PREPAID_SUBSCRIPTION",
    UNKNOWN = "UNKNOWN"
}

export enum PRORATION_MODE {
    UNKNOWN_SUBSCRIPTION_UPGRADE_DOWNGRADE_POLICY = 0,
    IMMEDIATE_WITH_TIME_PRORATION = 1,
    IMMEDIATE_AND_CHARGE_PRORATED_PRICE = 2,
    IMMEDIATE_WITHOUT_PRORATION = 3,
    DEFERRED = 6,
    IMMEDIATE_AND_CHARGE_FULL_PRICE = 5
}

// Import VERIFICATION_RESULT from wildberry-types instead of defining it here
export { VERIFICATION_RESULT } from 'wildberry-types';
